### ISSUE TITLE
Help adding narrowing feature to consult

### ISSUE THREAD

**Issue by atanasj** [publicimageltd/notmuch-bookmarks#2]
I am hoping for some help. I use consult and am trying to add to the add to the narrowing feature. I have done the following, but this does not seem to work. 

Original function in consults:

```elisp
(defcustom consult-bookmark-narrow
  `((?f "File" ,#'bookmark-default-handler)
    (?h "Help" ,#'help-bookmark-jump)
    (?i "Info" ,#'Info-bookmark-jump)
    (?p "Picture" ,#'image-bookmark-jump)
    (?d "Docview" ,#'doc-view-bookmark-jump)
    (?m "Man" ,#'Man-bookmark-jump)
    (?w "Woman" ,#'woman-bookmark-jump)
    (?g "Gnus" ,#'gnus-summary-bookmark-jump)
    ;; Introduced on Emacs 28
    (?s "Eshell" eshell-bookmark-jump)
    (?e "Eww" eww-bookmark-jump)
    (?v "VC Directory" vc-dir-bookmark-jump))
  "Bookmark narrowing configuration.

Each element of the list must have the form (char name handler)."
  :type '(repeat (list character string function)))
```
What I have tried to do:
```elisp
(eval-after-load 'consult
  '(progn
     (setq consult-bookmark-narrow
           (append consult-bookmark-narrow
                   '((?n "notmuch" ,#'notmuch-bookmarks-record-p)
                     )))))
```
This does not seem to work. Am I calling the correct function from notmuch-bookmarks?

**Comment by publicimageltd** [comment]
The following code works as expected:

```emacs-lisp
(seq-filter #'notmuch-bookmarks-record-p bookmark-alist)
```

It might be a wrong quote at the beginning of your assignment. You should use _`_ and not _'_ if you want to use the comma construct.  So maybe that works:

```emacs-lisp
(eval-after-load 'consult
  `(progn
     (setq consult-bookmark-narrow
           (append consult-bookmark-narrow
                   '((?n "notmuch" ,#'notmuch-bookmarks-record-p)
                     )))))

```

**Comment by atanasj** [comment]
Thanks, but this doesn't work. I have raised an issue on the consult repo and see what happens there.

**Comment by publicimageltd** [comment]
Did you try the new version I uploaded last week? It has built-in narrowing for consult bookmarks: Press 'n', and it should filter to all notmuch bookmarks. Actually I should make that a non-default option....

**Comment by atanasj** [comment]
Just got around to testing this. It's an excellent feature. Thanks!
